### ISSUE TITLE
Consider using http://ablog.readthedocs.io/

### ISSUE THREAD

**Issue by Blendify** [ThisWeekInBlenderDev/source#1]
We should consider using http://ablog.readthedocs.io/

**Comment by ideasman42** [comment]
Which features are useful compared to what we have?
Main one seems to be archived posts.
*(not against - just wondering)*

**Comment by Blendify** [comment]
That, an atom feed, Blog sidebars, Blog feeds, and maybe font awesome to make things look nice.

**Comment by ideasman42** [comment]
@Blendify +1 to try this out then :) could you commit this to the current repo?

**Comment by Blendify** [comment]
Yeah, I will work on in later tonight/tomorrow depending on the amount of time needed to set it up.

**Comment by ideasman42** [comment]
I tried this with the sphinx in requirements.txt and the latest sphinx, both failed with python exceptions.

Seems this extension is doing some complex stuff that breaks easily :S

While I'm not against using, it might be more trouble than its worth. We could just use RSS feed generator to begin with since its not causing problems.

**Comment by Blendify** [comment]
Yeah I got that too was going to try to look into it a little first to see if it can easily be fixed

**Comment by ideasman42** [comment]
I had a look at fixing the errors but they seem non-trivial *(fixing the first one was easy but other errors weren't)*.

Note there are quite a few options:

- https://getnikola.com
- http://docs.getpelican.com
- http://tinkerer.me

These are more heavy weight and intended for someone maintaining a personal blog, most of this I don't think we need.

Am still thinking it's probably easiest only to depend on light-weight extensions and keep it simple.

----

I've moved the ablog test to `ablog-wip` branch, since we can't get it working for the moment.

**Comment by Blendify** [comment]
Ok I think hat will be best for right now. My Idea now is that we can some how auto generate some of the data and try to generate the rst file each week. I am not sure how possible this is though. https://developer.blender.org/conduit/ should be able to help with some of this though. https://github.com/disqus/python-phabricator might be able to help with this and/or other projects.

**Comment by ideasman42** [comment]
Agree this would be good, added task #2 to handle this

**Comment by ideasman42** [comment]
Closing since ablog seems not really maintained.

**Comment by Blendify** [comment]
Sounds like a good idea
